# Kitty colors — Matugen Dynamic Colors

foreground              #e5e1e9
background              #141318
cursor                  #c8bfff
cursor_text_color       #30285f
selection_foreground    #e5dff9
selection_background    #474459

# Black
color0                  #201f25
color8                  #2b292f

# Red
color1                  #ffb4ab
color9                  #93000a

# Green
color2                  #ecb8ce
color10                 #613b4d

# Yellow
color3                  #c9c3dc
color11                 #474459

# Blue
color4                  #c8bfff
color12                 #473f77

# Magenta
color5                  #ecb8ce
color13                 #ffd8e7

# Cyan
color6                  #c9c3dc
color14                 #e5dff9

# White
color7                  #e5e1e9
color15                 #c9c5d0
